### STEP BY STEP
##### 1.Getting the data ready
##### 2.Choose the right estimator/algorithm for our problems
##### 3.Fit the model/algorithm and use it to make predictions on our data
##### 4.Evaluating a model
##### 5.Improve a model
##### 6.Save and load a trained model
##### 7.Putting it all together

### 0.An end-to-end scikit learn workflow

# SCROLL DOWN

# SCROLL DOWN

## 3.Fit the model/algorithm on our data and use it to make prediction

  ### 3.1 Fitting the model to the data
  diffrent names for:
  * 'X' = features,deatures variable,data
  * 'y' = lables,targets,targets variable

In [121]:
#import the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

#setup random seed
np.random.seed(42)

#make the data
X = hd.drop("target",axis = 1)
y = hd["target"]

#Split the data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

#Intantiate LinearSVC and fit the data
clf = RandomForestClassifier()
clf.fit(X_train,y_train)

#check score
clf.score(X_test,y_test)

0.8524590163934426

### 3.2 Make predictions using a machine learning model
2 wats to make predictions:
* predict()
* predict_proba()

In [125]:
#Use a trained model to make predictions
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [126]:
#Compare predictions to trusth labels to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

np.float64(0.8524590163934426)

In [127]:
clf.score(X_test,y_test)

0.8524590163934426

In [133]:
from sklearn.metrics import accuracy_score
accuracy_score = (X_test,y_test)

In [136]:
#predict_proba() returns probabilities of a cassification label
clf.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [137]:
#Let's predict on the same data
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1])